apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: docker.io/prajwalmalokar/frontend:latest
        env:
          - name: BACKEND_URL
            value: http://backend.default.svc.cluster.local
        ports:
        - containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  selector:
    app: frontend
  ports:
  - port: 80
    targetPort: 9000
  type: ClusterIP
